### ISSUE TITLE
Filter Excercises

### ISSUE THREAD

**Issue by Swahaha** [jess-che/fortis#3]
We need heirarchies of muscle groups: for example chest should be a subset of push s.t. when we filter by push, all chest excercises are displayed. This should be a subroutine added to Discover.tsx as needed.

This can be implemented via the database or just an array/tree in js.

**Comment by jess-che** [comment]
For this one could we do isa relationships kinda

**Comment by jess-che** [comment]
Actually we could just add a column aren’t all muscle groups a subsection of a section

**Comment by Swahaha** [comment]
Nice, yeah this is good way to do it.
